# -*- coding: utf-8 -*-
"""pdf2jpg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1auGOaKfFovm6XPOTtQ4w2N2jVduiflnh
"""
from __future__ import print_function
# !pip install pdf2jpg

# pip install pdf2image

from pdf2image.exceptions import (
    PDFInfoNotInstalledError,
    PDFPageCountError,
    PDFSyntaxError
)

#!apt-get install poppler-utils

images = convert_from_path('adt.pdf')

for i, image in enumerate(images):
    fname = "image" + str(i) + ".png"
    image.save(fname, "PNG")

import requests
import json

test_url = 'https://srivatsan.cognitiveservices.azure.com/customvision/v3.0/Prediction/4356d87c-8852-4b9c-8a39-5c6f59a62acb/detect/iterations/Iteration6/image'
#test_url = addr + '/api/test'
# prepare headers for http request
headers = {'Prediction-Key': "015257f7093647ad9b57ac05e3b6c085","Content-Type":"application/octet-stream"}
img_file = 'image0.png'
# encode image as jpe
#_, img_encoded = cv2.imencode('.jpg', img)
img = open(img_file, 'rb').read()
# send http request with image and receive response
response = requests.post(test_url,img, headers=headers)
# decode response
print(json.loads(response.text)['predictions'][0])

print(json.loads(response.text)['predictions'][1])

print(json.loads(response.text)['predictions'][0]['tagName'])
print(json.loads(response.text)['predictions'][1]['tagName'])

